@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.fish.journeytobaoji.waystone.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;