@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.fish.journeytobaoji.waystone.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;